export const MOTIVATIONAL_QUOTES = [
  "The best time to start was yesterday. The next best time is now.",
  "Small steps lead to big changes.",
  "You don't have to be great to start, but you have to start to be great.",
  "Progress, not perfection.",
  "Do it now. Sometimes 'later' becomes 'never'.",
  "One task at a time. You've got this.",
  "Your future self will thank you.",
  "Focus on the next right thing.",
  "Done is better than perfect.",
  "Every completed task is a win.",
  "Keep going. You're closer than you think.",
  "One hour of doing beats a day of planning.",
  "Start where you are. Use what you have.",
  "The only bad workout is the one that didn't happen. Same for tasks.",
  "You're capable of more than you know.",
  "Tick one box. Feel the progress.",
  "Momentum builds with action.",
  "Small wins compound.",
  "Just begin. The rest will follow.",
  "Today's effort is tomorrow's success.",
];
